[workspace]
members = [
    "apps/drocsid",
    "crates/cli",
    "crates/client",
    "crates/config",
    "crates/protocol",
    "crates/server",
    "crates/tui",
]
resolver = "3"

[workspace.package]
version = "0.2.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/kev1n999/drocsid"
