[workspace]
repo_url = "https://github.com/drocsid-supremo/drocsid"
changelog_update = false
git_tag_enable = false
git_release_enable = false
publish_timeout = "10m"

[[package]]
name = "drocsid"
git_tag_enable = true
git_tag_name = "v{{ version }}"
git_release_enable = false
