[package]
name = "drocsid-client"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "TCP client state and networking for drocsid."

[dependencies]
drocsid-config = { version = "0.3.0", path = "../config" }
drocsid-protocol = { version = "0.3.0", path = "../protocol" }
tracing = "0.1"
