[package]
name = "drocsid"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "A terminal chat client and server written in Rust."

[dependencies]
drocsid-cli = { version = "0.2.0", path = "../../crates/cli" }
drocsid-config = { version = "0.2.0", path = "../../crates/config" }
drocsid-server = { version = "0.2.0", path = "../../crates/server" }
drocsid-tui = { version = "0.2.0", path = "../../crates/tui" }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = [
    "precommit-hook",
    "run-cargo-fmt",
    "run-cargo-clippy",
    "run-cargo-test",
]
