[package]
name = "drocsid-tui"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Ratatui terminal interface for drocsid."

[dependencies]
crossterm = "0.29"
drocsid-client = { version = "0.2.1", path = "../client" }
drocsid-config = { version = "0.2.1", path = "../config" }
drocsid-protocol = { version = "0.2.1", path = "../protocol" }
ratatui = "0.30.1"
tracing = "0.1"
